### ISSUE TITLE
Mining

### ISSUE THREAD

**Issue by you-li-nu** [freewil/bitcoin-testnet-box#38]
Hello, in the Makefile one can assign one node to generate a certain number of blocks. Also, it seems one can initiate more than two nodes. My question is, instead to explicitly assign which node to generate a new block, is it possible to have two or more nodes compete on a new block? Thanks!

**Comment by freewil** [comment]
This project at one point did actual mining (privately), but with a fork of bitcoind that made it much easier to find a block. If you look at the commit history for this project from October 2014, you can see the project was switched over to use the official bitcoind PPA, instead of the [easy-mining fork](https://github.com/freewil/bitcoin/tree/easy-mining), and now uses [regtest](https://bitcoin.org/en/developer-examples#regtest-mode), which I believe would disallow any possible competition for a block, as it is designed to allow a node to instantly find a block.

Regtest is great for most developers building applications on top of bitcoin, but if you actually wanted to better understand mining and see 2 miners compete for a block, then I would suggest reverting back to a similar behavior (but with the most recent version of bitcoind) without regtest.
